# Generated by Django 4.2.2 on 2023-07-05 00:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_producto_descripcion_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.descuento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 20, 27, 49, 853201)),
        ),
    ]
