# Generated by Django 4.2.2 on 2023-07-05 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_producto_descuento_aplicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 20, 39, 34, 337095)),
        ),
    ]
